name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: تنزيل ملفاتي من المستودع
        uses: actions/checkout@v4
        with:
          path: my_files

      - name: تجهيز Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable

      - name: إنشاء هيكل تطبيق Flutter كامل (android/ios) تلقائيًا
        run: flutter create --platforms=android app

      - name: نسخ الكود الخاص بي داخل الهيكل
        run: |
          cp my_files/pubspec.yaml app/pubspec.yaml
          rm -rf app/lib
          cp -r my_files/lib app/lib

      - name: تنزيل الحزم
        working-directory: app
        run: flutter pub get

      - name: بناء ملف APK
        working-directory: app
        run: flutter build apk --release

      - name: رفع ملف APK كنتيجة نهائية
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk
